### ISSUE TITLE
bout_runners examples crash with TypeError

### ISSUE THREAD

**Issue by steve-biggs** [boutproject/BOUT-dev#1183]
All the ones I tested (1-5) crash with the same error (below). I've tried making a fresh python virtual environment and I've tried both python2 and python3. scipy and boutdata import fine. bout_runners imports fine. As per the stack trace below, the problem occurs when the runner is executed. Looks to me like possibly the runner code has been updated but the examples have not?

```


getmpirun: using the default mpirun -np
Traceback (most recent call last):
  File "1-basic_driver.py", line 11, in <module>
    my_runs.execute_runs()
  File "/home/userfs/s/snb519/Programs/BOUT/tools/pylib/bout_runners/bout_runners.py", line 609, in execute_runs
    post_process_after_every_run)
  File "/home/userfs/s/snb519/Programs/BOUT/tools/pylib/bout_runners/bout_runners.py", line 1589, in _error_check_for_run_input
    (isinstance(post_processing_function, None)):
TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types
```

**Comment by d7919** [comment]
I can reproduce this. Changing line 1589 of bout_runners.py from `isinstance(post_processing_function, None)` to `type(post_processing_function) is None` seems to fix this. This inverse of this change (i.e. the "broken" behaviour) was introduced in 8a5f3a7716f1ae00e7d36a98789aaaf006c0b774

**Comment by bendudson** [comment]
Sorry; I merged this without testing, since this is Michael's baby. Is it possible to add some tests for this, ideally in addition to tests for other parts of the python tools?

**Comment by ZedThree** [comment]
Definitely in need of some tests. I think some parts will need mock objects or something-- it would be better if the tests didn't compile and run actual models for instance. We should also consider moving it out of BOUT-dev into e.g. boutprojects/BOUT-runner

---

For this particular problem, I think the correct thing is

```python
        if (post_process_after_every_run and
            post_processing_function is None):
 ```

This still fails because the default values for these are inconsistent -- `True` and `None`, respectively. In 92f71e8833fd707be751b1e78ee36f888a6b8ed3 `post_process_after_every_run` had its default changed from `None` to `True`, which explains why the conditional is currently

```py
        if (post_process_after_every_run is not None) and\
           (isinstance(post_processing_function, None)):
```

Note that both `True` and `False` are `not None`, so this doesn't look like the expected behaviour.
