### ISSUE TITLE
Making grid index routines public

### ISSUE THREAD

**Issue by loeiten** [boutproject/BOUT-dev#225]
Is there a reason for why the grid index routines (line 136-144 in `boutmesh.hxx`) are `private`?
If not, would it be OK if I made these `public`?

The same question applies for the data which are given in `BOUT.inp` or a grid file (for example `nx` and `ny`). I have no need (currently) to make these public, but I can see these can be handy to access from time to time.

**Comment by bendudson** [comment]
The reason I've been reluctant to make these public is that it makes future changes to the mesh harder. For example nx and ny are currently constants, but in an irregularly shaped mesh might not be. The grid index routines in boutmesh.hxx really only handle the case where NXPE and NYPE are fixed, so for exampe NXPE doesn't depend on y position. 

I agree some kind of public mapping from local to global index would be useful, or finding which processor contains point (x,y,z), but I'd prefer them to be more general if possible.

**Comment by loeiten** [comment]
I see, that makes sense.

A possible solution could be to throw a `NotImplemented` on these methods in mesh-classes where `NXPE` and `NYPE` are not fixed. Eventually they could deprecate and go back to being `private` if a general method is made.

**Comment by loeiten** [comment]
Closing this, see discussion in #226 for details.
